"""
Pydantic data models for Master Profile, JD Extraction, Gap Analysis,
Tailored Resume, Grounding Verification, and ATS Format Validation.
Matches the schemas defined in Technical_Architecture.md §3.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


# ==========================================
# STAGE 1: MASTER PROFILE SCHEMAS
# ==========================================

class PersonalInfo(BaseModel):
    full_name: str = ""
    email: str = ""
    phone: str = ""
    location: str = ""
    linkedin_url: str = ""
    portfolio_url: str = ""


class BulletPoint(BaseModel):
    id: str = Field(description="Unique bullet ID (e.g., b_1)")
    text: str = Field(description="Bullet point content")
    skills_tags: List[str] = Field(default_factory=list, description="Skills demonstrated in this bullet")
    metrics: List[str] = Field(default_factory=list, description="Measurable achievements/metrics in this bullet")


class WorkExperience(BaseModel):
    id: str = Field(description="Unique experience ID (e.g., we_1)")
    company: str = ""
    title: str = ""
    location: str = ""
    start_date: Optional[str] = Field(default=None, description="YYYY-MM or YYYY")
    end_date: Optional[str] = Field(default=None, description="YYYY-MM, YYYY, or Present")
    is_current: bool = False
    bullets: List[BulletPoint] = Field(default_factory=list)


class Education(BaseModel):
    id: str = Field(description="Unique education ID (e.g., ed_1)")
    institution: str = ""
    degree: str = ""
    field: str = ""
    graduation_date: Optional[str] = Field(default=None, description="YYYY-MM or YYYY")


class SkillCategories(BaseModel):
    technical: List[str] = Field(default_factory=list, description="Languages, frameworks, core hard skills")
    tools: List[str] = Field(default_factory=list, description="Software, platforms, developer tools")
    soft: List[str] = Field(default_factory=list, description="Leadership, communication, organizational skills")
    languages: List[str] = Field(default_factory=list, description="Spoken languages")


class ProjectItem(BaseModel):
    id: str = Field(description="Unique project ID (e.g., proj_1 or github_repo)")
    name: str = ""
    source: str = Field(default="manual", description="github | portfolio | local | manual")
    source_ref: str = Field(default="", description="Repo URL, portfolio URL, or local path")
    description_raw: str = Field(default="", description="Untouched README / commit text / source material")
    draft_bullets: List[str] = Field(default_factory=list, description="Candidate bullets generated by LLM Project Extraction")
    tech_stack: List[str] = Field(default_factory=list, description="Detected or declared tech stack")
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    last_active_date: Optional[str] = None
    visibility: str = Field(default="public", description="public | private | unknown")
    links: Dict[str, str] = Field(default_factory=dict)
    review_flags: List[str] = Field(default_factory=list, description="Flags for confidentiality or ambiguity")
    reviewed_by_user: bool = Field(
        default=False,
        description="Gate: Stage 5 tailoring must never read a project where this is False (PRD.md §8)"
    )


class MasterProfile(BaseModel):
    personal_info: PersonalInfo = Field(default_factory=PersonalInfo)
    summary: str = ""
    work_experience: List[WorkExperience] = Field(default_factory=list)
    education: List[Education] = Field(default_factory=list)
    skills: SkillCategories = Field(default_factory=SkillCategories)
    certifications: List[str] = Field(default_factory=list)
    projects: List[ProjectItem] = Field(default_factory=list)
    achievements: List[str] = Field(default_factory=list)

    def ensure_unique_ids(self) -> None:
        """Ensure all work experiences, bullets, education, and projects have valid, unique IDs."""
        bullet_counter = 1
        for idx, exp in enumerate(self.work_experience, 1):
            if not exp.id or exp.id == "":
                exp.id = f"we_{idx}"
            for b in exp.bullets:
                if not b.id or b.id == "":
                    b.id = f"b_{bullet_counter}"
                bullet_counter += 1

        for idx, edu in enumerate(self.education, 1):
            if not edu.id or edu.id == "":
                edu.id = f"ed_{idx}"

        for idx, proj in enumerate(self.projects, 1):
            if not proj.id or proj.id == "":
                proj.id = f"proj_{idx}"

    def get_all_bullets(self) -> Dict[str, BulletPoint]:
        """Return a mapping of bullet_id -> BulletPoint across all work experiences."""
        mapping = {}
        for exp in self.work_experience:
            for b in exp.bullets:
                mapping[b.id] = b
        return mapping

    def get_approved_projects(self) -> List[ProjectItem]:
        """Return only projects that have been reviewed and approved by user."""
        return [p for p in self.projects if p.reviewed_by_user]


# ==========================================
# STAGE 3: JD EXTRACTION SCHEMAS
# ==========================================

class RequirementItem(BaseModel):
    requirement: str
    category: str = Field(
        default="hard_skill",
        description="hard_skill | soft_skill | tool | certification | experience_years | education"
    )
    keywords: List[str] = Field(default_factory=list, description="Keywords including acronyms and full terms")


class CompanyContext(BaseModel):
    industry: str = ""
    size: str = ""
    notes: str = ""


class JDExtraction(BaseModel):
    job_title: str = ""
    company: str = ""
    seniority_level: str = ""
    employment_type: str = ""
    must_have_requirements: List[RequirementItem] = Field(default_factory=list)
    nice_to_have_requirements: List[str] = Field(default_factory=list)
    core_responsibilities: List[str] = Field(default_factory=list)
    keywords_for_ats: List[str] = Field(default_factory=list)
    company_context: CompanyContext = Field(default_factory=CompanyContext)


# ==========================================
# STAGE 4: GAP & MATCH ANALYSIS SCHEMAS
# ==========================================

class GapAnalysisResult(BaseModel):
    matched_keywords: List[str] = Field(default_factory=list)
    missing_keywords: List[str] = Field(default_factory=list)
    keyword_coverage_pct: float = 0.0
    matched_must_haves: List[RequirementItem] = Field(default_factory=list)
    unmatched_must_haves: List[RequirementItem] = Field(default_factory=list)
    must_have_coverage_pct: float = 0.0
    unmatched_nice_to_haves: List[str] = Field(default_factory=list)


# ==========================================
# STAGE 5: TAILORED RESUME SCHEMAS
# ==========================================

class TailoredBullet(BaseModel):
    source_bullet_id: str = Field(description="Must point to a valid bullet ID in MasterProfile")
    tailored_text: str = Field(description="Tailored phrasing mirroring JD language")


class TailoredExperience(BaseModel):
    id: str  # we_1
    company: str
    title: str
    location: str
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    is_current: bool = False
    bullets: List[TailoredBullet] = Field(default_factory=list)


class TailoredResume(BaseModel):
    job_id_ref: str = ""
    target_job_title: str = ""
    target_company: str = ""
    generated_at: str = ""
    summary: str = ""
    selected_experience: List[TailoredExperience] = Field(default_factory=list)
    selected_education: List[Education] = Field(default_factory=list)
    selected_skills: SkillCategories = Field(default_factory=SkillCategories)
    selected_certifications: List[str] = Field(default_factory=list)
    selected_projects: List[ProjectItem] = Field(default_factory=list)
    selected_achievements: List[str] = Field(default_factory=list)
    unmatched_must_haves_notes: List[str] = Field(
        default_factory=list,
        description="Must-haves from JD that Master Profile does not support - for candidate awareness"
    )


# ==========================================
# STAGE 6: GROUNDING CHECK SCHEMAS
# ==========================================

class GroundingIssue(BaseModel):
    source_id: str
    tailored_text: str
    reason: str
    severity: str = Field(default="error", description="error (unsupported fact) | warning (stretch)")


class GroundingCheckResult(BaseModel):
    passed: bool = True
    unsupported_claims: List[GroundingIssue] = Field(default_factory=list)


# ==========================================
# STAGE 7: ATS FORMAT VALIDATION SCHEMAS
# ==========================================

class ATSValidationIssue(BaseModel):
    rule: str
    message: str
    severity: str = Field(default="error", description="error | warning")


class ATSValidationResult(BaseModel):
    passed: bool = True
    score: int = 100
    issues: List[ATSValidationIssue] = Field(default_factory=list)


# ==========================================
# STAGE 10: VERSION STORE SCHEMAS
# ==========================================

class VersionRecord(BaseModel):
    version_id: str
    company: str
    job_title: str
    date: str
    docx_path: str
    pdf_path: Optional[str] = None
    jd_snapshot_path: Optional[str] = None
    keyword_coverage_pct: float = 0.0
    ats_score: int = 100
    grounding_passed: bool = True


# ==========================================
# FR-10: COVER LETTER SCHEMAS
# ==========================================

class CoverLetter(BaseModel):
    job_id_ref: str = ""
    target_company: str = ""
    target_job_title: str = ""
    generated_at: str = ""
    recipient_title: str = "Hiring Manager"
    salutation: str = "Dear Hiring Team,"
    opening: str = ""
    body_paragraphs: List[str] = Field(default_factory=list)
    closing: str = ""
    full_text: str = ""
    grounded_bullet_refs: List[str] = Field(default_factory=list)

